name: A workflow for my Hello World File
on:
    workflow_dispatch:
    push:
     paths:
        - ! .github/**
jobs:
    build-job:
        name: Hello world job 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
          name: Check out code
        - name: Echo Hello World
          run: echo Hello World
        - name: index.html content
          run: |
            echo "This is line 1"
            echo "This is line 2"
            cat index.html
            cat courses.html
